[package]
name = "instock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "*"
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "postgres", "macros", "json" ] }
tokio = { version = "^1.0", features = ["full"] }
reqwest="0.11.9"
scraper = "*"
futures = "*"
serde = "*"
anyhow = "*"