
FROM rust:1.58 as builder 

WORKDIR /app

COPY . . 

ENV SQLX_OFFLINE=true

RUN cargo build --release


FROM debian:bullseye-slim AS runtime

WORKDIR /app

RUN apt-get update -y \
    && apt-get install -y --no-install-recommends ca-certificates \
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/release/instock instock

ENTRYPOINT ["./instock"]